//! Shared GNSS constants.
//!
//! These are semantic constants used across multiple GNSS modules. A parity
//! target may still keep a local alias or comment when the operation order of a
//! formula matters, but the source value lives here so modules do not drift.

pub use crate::astro::constants::astro::{AU_KM, AU_M};
pub use crate::astro::constants::earth::{
    MEAN_EARTH_RADIUS_M, OMEGA_E_DOT_RAD_S, WGS84_A_KM, WGS84_A_M, WGS84_E2, WGS84_F,
};
pub use crate::astro::constants::geometry::AZIMUTH_ZENITH_EPS;
pub use crate::astro::constants::time::{J2000_JD, SECONDS_PER_DAY, SECONDS_PER_WEEK};
pub use crate::astro::constants::units::{
    DEGREES_PER_CIRCLE, DEGREES_PER_SEMICIRCLE, DEG_TO_RAD, KM_TO_M, MICROSECONDS_PER_SECOND,
    MM_PER_M, M_PER_KM, RAD_TO_DEG, US_TO_S,
};

/// Seconds in half a GNSS week, the rollover fold threshold.
pub const HALF_WEEK_S: f64 = SECONDS_PER_WEEK / 2.0;

/// Speed of light in vacuum (m/s), IS-GPS-200. Re-exported from the canonical
/// core home so the value is defined once for the whole workspace.
pub const C_M_S: f64 = crate::astro::constants::physics::SPEED_OF_LIGHT_M_S;

/// GPS L1 carrier frequency (Hz). Galileo E1 shares this frequency.
pub const F_L1_HZ: f64 = 1_575.42e6;

/// GPS L2 carrier frequency (Hz).
pub const F_L2_HZ: f64 = 1_227.60e6;

/// Galileo E1 carrier frequency (Hz). GPS L1 shares this frequency.
pub const F_E1_HZ: f64 = F_L1_HZ;

/// Galileo E5a carrier frequency (Hz).
pub const F_E5A_HZ: f64 = 1_176.45e6;

/// BeiDou B1I carrier frequency (Hz).
pub const F_B1I_HZ: f64 = 1_561.098e6;

/// BeiDou B3I carrier frequency (Hz).
pub const F_B3I_HZ: f64 = 1_268.52e6;

/// Seconds from GPS epoch (1980-01-06 00:00) to J2000 (2000-01-01 12:00).
pub const GPS_EPOCH_TO_J2000_S: f64 = 630_763_200.0;

/// GPS Time minus BeiDou Time (seconds): BDT = GPST - 14 s.
pub const GPST_MINUS_BDT_S: f64 = 14.0;

/// GPS/Galileo/QZSS and BeiDou system-time-minus-TAI offsets. Canonically
/// defined in the always-on astro time-constants module (the always-present
/// `astro::time` scale layer needs them); re-exported here for GNSS consumers.
pub use crate::astro::constants::time::{BDT_MINUS_TAI_S, GPST_MINUS_TAI_S};

/// Seconds from the GPS epoch to the BeiDou epoch (2006-01-01).
pub const BDS_EPOCH_MINUS_GPS_EPOCH_S: f64 = 1356.0 * SECONDS_PER_WEEK;

/// Fixed transmit-time iterations for SPP residuals.
///
/// The SPP solver is pinned to two iterations by the SPP trace fixtures. The
/// observable predictor deliberately uses a separate three-iteration policy
/// because it mirrors Sidereon `Observables.predict` and its own SP3 oracle.
pub const SPP_TRANSMIT_TIME_ITERATIONS: usize = 2;

/// Fixed transmit-time iterations for observable prediction.
///
/// Kept distinct from [`SPP_TRANSMIT_TIME_ITERATIONS`] after oracle
/// reconciliation: the public observable predictor performs three light-time
/// refinement iterations plus the final transmit-epoch evaluation.
pub const OBSERVABLE_TRANSMIT_TIME_ITERATIONS: usize = 3;

/// Default SP3 provenance comment emitted when a product has no comments.
pub const SP3_DEFAULT_PROVENANCE_COMMENT: &str = "Generated by sidereon-core";
