// Fixture provenance: `tests/fixtures/trf_data_problem.json` is generated by the
// committed script `crates/trust-region-least-squares/fixtures-generators/generate_trf_data_problem.py`.
// Reference oracle: SciPy 1.18.0 `optimize.least_squares` with TRF, dense exact
// solver, two-point Jacobian, `gtol=1e-10`, for each `BuiltinResidual` kind
// (`linear`/`polynomial`/`exponential`) crossed with every loss
// (`linear`/`soft_l1`/`huber`/`cauchy`/`arctan`). Each case is rebuilt as a
// `DataProblem` and replayed end-to-end through `solve_data_problem_with` with the
// host-LAPACK SVD/BLAS backend, and the full result is compared bit-for-bit. This
// is the bit-exact bar for the data-driven path.
// Pinned generation environment: Python 3.12.3, NumPy 2.5.0, SciPy 1.18.0,
// Linux x86_64 with SciPy's bundled OpenBLAS (OPENBLAS_NUM_THREADS=1, fixed
// OPENBLAS_CORETYPE), matching the rest of the bit-exact suite. All floating-point
// payloads are serialized as f64 hex-bit strings and must be compared with
// `f64::to_bits`, never tolerances.
//
// Like `general_fixtures.rs`, this replay needs a host LAPACK/BLAS pointed at by
// `TRUST_REGION_LEAST_SQUARES_LAPACK_PATH` (the SciPy/NumPy that generated the
// fixture); it skips when that is not configured.
use std::collections::BTreeSet;
use std::path::PathBuf;

use serde_json::Value;
use trust_region_least_squares::data::{solve_data_problem_with, BuiltinResidual, DataProblem};
use trust_region_least_squares::hostlapack::LapackSvd;
use trust_region_least_squares::loss::Loss;
use trust_region_least_squares::parity::{
    assert_f64_bits_eq, assert_f64_slice_bits_eq, f64_from_hex,
};

#[path = "support/bitexact.rs"]
mod bitexact;

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn bits(value: &Value) -> f64 {
    f64_from_hex(value.as_str().expect("hex-bit string")).expect("valid f64 bits")
}

fn bits_vec(value: &Value) -> Vec<f64> {
    value
        .as_array()
        .expect("hex-bit array")
        .iter()
        .map(bits)
        .collect()
}

fn loss_from_str(name: &str) -> Loss {
    match name {
        "linear" => Loss::Linear,
        "soft_l1" => Loss::SoftL1,
        "huber" => Loss::Huber,
        "cauchy" => Loss::Cauchy,
        "arctan" => Loss::Arctan,
        other => panic!("unknown loss {other}"),
    }
}

fn builtin_from_case(case: &Value) -> BuiltinResidual {
    match case["kind"].as_str().expect("kind") {
        "linear" => BuiltinResidual::Linear {
            a: bits_vec(&case["a"]),
            b: bits_vec(&case["b"]),
            m: case["m"].as_u64().expect("m") as usize,
            n: case["n"].as_u64().expect("n") as usize,
        },
        "polynomial" => BuiltinResidual::Polynomial {
            degree: case["degree"].as_u64().expect("degree") as usize,
            t: bits_vec(&case["t"]),
            y: bits_vec(&case["y"]),
        },
        "exponential" => BuiltinResidual::Exponential {
            t: bits_vec(&case["t"]),
            y: bits_vec(&case["y"]),
        },
        other => panic!("unknown kind {other}"),
    }
}

fn skip_if_host_lapack_path_missing() -> bool {
    if std::env::var("TRUST_REGION_LEAST_SQUARES_LAPACK_PATH").is_err() {
        eprintln!("skipping host-lapack parity: TRUST_REGION_LEAST_SQUARES_LAPACK_PATH not set");
        true
    } else {
        false
    }
}

#[test]
fn scipy_trf_data_problem_hostlapack_results_are_bit_exact() {
    if bitexact::skip_platform_pinned_replay() {
        return;
    }
    if skip_if_host_lapack_path_missing() {
        return;
    }

    let raw = std::fs::read_to_string(fixture_path("trf_data_problem.json"))
        .expect("read trf data-problem fixture");
    let doc: Value = serde_json::from_str(&raw).expect("parse trf data-problem fixture");
    assert_eq!(
        doc["schema"],
        "trust-region-least-squares-trf-data-problem-v1"
    );
    assert_eq!(doc["reference"]["scipy"], "1.18.0");
    assert_eq!(doc["reference"]["numpy"], "2.5.0");

    let svd = LapackSvd::from_env();
    let mut checked = 0usize;
    let mut kinds_seen = BTreeSet::new();
    let mut losses_seen = BTreeSet::new();

    for case in doc["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("case name");
        let kind = builtin_from_case(case);
        let loss = loss_from_str(case["loss"].as_str().expect("loss"));
        let f_scale = bits(&case["f_scale"]);
        let x0 = bits_vec(&case["x0"]);
        kinds_seen.insert(case["kind"].as_str().unwrap().to_string());
        losses_seen.insert(case["loss"].as_str().unwrap().to_string());

        let problem = DataProblem {
            loss,
            f_scale,
            ..DataProblem::new(kind, x0)
        };

        let result =
            solve_data_problem_with(&problem, &svd).expect("host LAPACK data-problem solve");

        assert_eq!(
            result.nfev,
            case["result"]["nfev"].as_u64().expect("nfev") as usize,
            "{name} nfev"
        );
        assert_eq!(
            result.njev,
            case["result"]["njev"].as_u64().expect("njev") as usize,
            "{name} njev"
        );
        assert_eq!(
            result.status,
            case["result"]["status"].as_i64().expect("status") as i32,
            "{name} status"
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result x"),
            &result.x,
            &bits_vec(&case["result"]["x"]),
        );
        assert_f64_bits_eq(
            &format!("{name} result cost"),
            result.cost,
            bits(&case["result"]["cost"]),
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result fun"),
            &result.fun,
            &bits_vec(&case["result"]["fun"]),
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result jac"),
            &result.jac,
            &bits_vec(&case["result"]["jac"]),
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result grad"),
            &result.grad,
            &bits_vec(&case["result"]["grad"]),
        );
        assert_f64_bits_eq(
            &format!("{name} result optimality"),
            result.optimality,
            bits(&case["result"]["optimality"]),
        );

        checked += 1;
    }

    assert!(checked > 0, "empty trf data-problem fixture");
    assert_eq!(
        kinds_seen,
        ["exponential", "linear", "polynomial"]
            .iter()
            .map(|s| s.to_string())
            .collect::<BTreeSet<_>>(),
        "expected every kind in the fixture"
    );
    assert_eq!(
        losses_seen,
        ["arctan", "cauchy", "huber", "linear", "soft_l1"]
            .iter()
            .map(|s| s.to_string())
            .collect::<BTreeSet<_>>(),
        "expected every loss in the fixture"
    );
}
