#![cfg(feature = "host-lapack")]

// Fixture provenance: `tests/fixtures/hostlapack_svd.json` is generated by the
// committed script `crates/trust-region-least-squares/fixtures-generators/generate_hostlapack_svd.py`.
// Reference oracle: SciPy 1.11.3 / NumPy 1.26.0 `scipy.linalg.svd(...,
// lapack_driver="gesdd", full_matrices=False)`. This payload is platform- and
// LAPACK-library-sensitive; Tier 2 replay must run in the pinned container named by
// the host-LAPACK workflow. Inputs are deterministic synthetic dense problems from
// the generator.
// Pinned generation environment: Python 3.11.15, NumPy 1.26.0, SciPy 1.11.3,
// PyProj 3.6.1, macOS-26.5.1-arm64. All floating-point payloads are serialized as
// f64 hex-bit strings and must be compared with `f64::to_bits`, never tolerances.
use std::path::PathBuf;

use serde_json::Value;
use trust_region_least_squares::hostlapack::LapackSvd;
use trust_region_least_squares::loss::Loss;
use trust_region_least_squares::parity::{
    assert_f64_bits_eq, assert_f64_slice_bits_eq, f64_from_hex,
};
use trust_region_least_squares::trf::{
    jacobian_2point, trf_no_bounds, JacobianFn, ResidualFn, ThinSvd, TrfOptions,
};

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn bits(value: &Value) -> f64 {
    f64_from_hex(value.as_str().expect("hex-bit string")).expect("valid f64 bits")
}

fn bits_vec(value: &Value) -> Vec<f64> {
    value
        .as_array()
        .expect("hex-bit array")
        .iter()
        .map(bits)
        .collect()
}

fn bits3(value: &Value) -> [f64; 3] {
    let v = bits_vec(value);
    [v[0], v[1], v[2]]
}

fn skip_if_host_lapack_path_missing() -> bool {
    if std::env::var("TRUST_REGION_LEAST_SQUARES_LAPACK_PATH").is_err() {
        eprintln!("skipping host-lapack parity: TRUST_REGION_LEAST_SQUARES_LAPACK_PATH not set");
        true
    } else {
        false
    }
}

fn residual_values(matrix: &[f64], target: &[f64], x: &[f64]) -> Vec<f64> {
    let m = target.len();
    let mut out = Vec::with_capacity(m);
    for (i, &target_i) in target.iter().enumerate().take(m) {
        let row = i * 3;
        out.push(matrix[row] * x[0] + matrix[row + 1] * x[1] + matrix[row + 2] * x[2] - target_i);
    }
    out[0] += (0.25 * x[0]).sin() + 0.01 * x[1] * x[1];
    out[1] += (0.20 * x[1]).cos() - 0.02 * x[0] * x[2];
    out[2] += (0.15 * x[2]).sin() + 0.03 * x[0];
    out
}

#[test]
fn scipy_hostlapack_svd_fixtures_are_bit_exact() {
    if skip_if_host_lapack_path_missing() {
        return;
    }

    let raw = std::fs::read_to_string(fixture_path("hostlapack_svd.json"))
        .expect("read hostlapack fixture");
    let doc: Value = serde_json::from_str(&raw).expect("parse hostlapack fixture");
    assert_eq!(
        doc["schema"],
        "trust-region-least-squares-hostlapack-svd-v1"
    );
    assert_eq!(doc["scipy_version"], "1.11.3");
    assert_eq!(doc["numpy_version"], "1.26.0");

    let svd = LapackSvd::from_env();
    let mut checked = 0usize;
    for case in doc["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("name");
        let m = case["m"].as_u64().expect("m") as usize;
        let n = case["n"].as_u64().expect("n") as usize;
        let a = bits_vec(&case["a_bits"]);
        let (u, s, vt) = svd.svd(&a, m, n).expect("host LAPACK SVD");
        assert_f64_slice_bits_eq(&format!("{name} u"), &u, &bits_vec(&case["u_bits"]));
        assert_f64_slice_bits_eq(&format!("{name} s"), &s, &bits_vec(&case["s_bits"]));
        assert_f64_slice_bits_eq(&format!("{name} vt"), &vt, &bits_vec(&case["vt_bits"]));
        checked += 1;
    }
    assert!(checked > 0, "empty hostlapack fixture");
}

#[test]
fn scipy_trf_small_dense_hostlapack_results_are_bit_exact() {
    if skip_if_host_lapack_path_missing() {
        return;
    }

    let raw =
        std::fs::read_to_string(fixture_path("trf_small_dense.json")).expect("read trf fixture");
    let doc: Value = serde_json::from_str(&raw).expect("parse trf fixture");
    assert_eq!(
        doc["schema"],
        "trust-region-least-squares-trf-small-dense-v1"
    );
    assert_eq!(doc["reference"]["scipy"], "1.11.3");
    assert_eq!(doc["reference"]["numpy"], "1.26.0");

    let svd = LapackSvd::from_env();
    let mut checked = 0usize;
    for case in doc["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("case name");
        let m = case["m"].as_u64().expect("m") as usize;
        let matrix = bits_vec(&case["matrix"]);
        let target = bits_vec(&case["target"]);
        assert_eq!(matrix.len(), m * 3, "{name} matrix length");
        assert_eq!(target.len(), m, "{name} target length");

        let mut fun = |x: &[f64], out: &mut Vec<f64>| {
            out.clear();
            out.extend(residual_values(&matrix, &target, x));
        };
        let mut jac = |x: &[f64], f0: &[f64], out: &mut Vec<f64>| {
            let mut scratch = Vec::new();
            let mut jac_fun = |x: &[f64], out: &mut Vec<f64>| {
                out.clear();
                out.extend(residual_values(&matrix, &target, x));
            };
            jacobian_2point(&mut jac_fun, x, f0, out, &mut scratch).expect("2-point jacobian");
        };

        let result = trf_no_bounds(
            &mut fun as &mut ResidualFn<'_>,
            &mut jac as &mut JacobianFn<'_>,
            &bits3(&case["x0"]),
            &svd,
            &TrfOptions::default(),
        )
        .expect("host LAPACK trf");

        assert_eq!(
            result.nfev,
            case["result"]["nfev"].as_u64().expect("nfev") as usize,
            "{name} nfev"
        );
        assert_eq!(
            result.njev,
            case["result"]["njev"].as_u64().expect("njev") as usize,
            "{name} njev"
        );
        assert_eq!(
            result.status,
            case["result"]["status"].as_i64().expect("status") as i32,
            "{name} status"
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result x"),
            &result.x,
            &bits_vec(&case["result"]["x"]),
        );
        assert_f64_bits_eq(
            &format!("{name} result cost"),
            result.cost,
            bits(&case["result"]["cost"]),
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result fun"),
            &result.fun,
            &bits_vec(&case["result"]["fun"]),
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result jac"),
            &result.jac,
            &bits_vec(&case["result"]["jac"]),
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result grad"),
            &result.grad,
            &bits_vec(&case["result"]["grad"]),
        );
        assert_f64_bits_eq(
            &format!("{name} result optimality"),
            result.optimality,
            bits(&case["result"]["optimality"]),
        );

        checked += 1;
    }
    assert!(checked > 0, "empty trf fixture");
}

fn loss_from_str(name: &str) -> Loss {
    match name {
        "linear" => Loss::Linear,
        "soft_l1" => Loss::SoftL1,
        "huber" => Loss::Huber,
        "cauchy" => Loss::Cauchy,
        "arctan" => Loss::Arctan,
        other => panic!("unknown loss {other}"),
    }
}

#[test]
fn scipy_trf_loss_hostlapack_results_are_bit_exact() {
    if skip_if_host_lapack_path_missing() {
        return;
    }

    let raw =
        std::fs::read_to_string(fixture_path("trf_loss.json")).expect("read trf loss fixture");
    let doc: Value = serde_json::from_str(&raw).expect("parse trf loss fixture");
    assert_eq!(doc["schema"], "trust-region-least-squares-trf-loss-v1");
    assert_eq!(doc["reference"]["scipy"], "1.11.3");
    assert_eq!(doc["reference"]["numpy"], "1.26.0");

    let svd = LapackSvd::from_env();
    let mut checked = 0usize;
    let mut losses_seen = std::collections::BTreeSet::new();
    for case in doc["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("case name");
        let loss = loss_from_str(case["loss"].as_str().expect("loss"));
        let f_scale = bits(&case["f_scale"]);
        let m = case["m"].as_u64().expect("m") as usize;
        let matrix = bits_vec(&case["matrix"]);
        let target = bits_vec(&case["target"]);
        assert_eq!(matrix.len(), m * 3, "{name} matrix length");
        assert_eq!(target.len(), m, "{name} target length");
        losses_seen.insert(case["loss"].as_str().unwrap().to_string());

        let mut fun = |x: &[f64], out: &mut Vec<f64>| {
            out.clear();
            out.extend(residual_values(&matrix, &target, x));
        };
        let mut jac = |x: &[f64], f0: &[f64], out: &mut Vec<f64>| {
            let mut scratch = Vec::new();
            let mut jac_fun = |x: &[f64], out: &mut Vec<f64>| {
                out.clear();
                out.extend(residual_values(&matrix, &target, x));
            };
            jacobian_2point(&mut jac_fun, x, f0, out, &mut scratch).expect("2-point jacobian");
        };

        let options = TrfOptions {
            loss,
            f_scale,
            ..TrfOptions::default()
        };
        let result = trf_no_bounds(
            &mut fun as &mut ResidualFn<'_>,
            &mut jac as &mut JacobianFn<'_>,
            &bits3(&case["x0"]),
            &svd,
            &options,
        )
        .expect("host LAPACK trf");

        assert_eq!(
            result.nfev,
            case["result"]["nfev"].as_u64().expect("nfev") as usize,
            "{name} nfev"
        );
        assert_eq!(
            result.njev,
            case["result"]["njev"].as_u64().expect("njev") as usize,
            "{name} njev"
        );
        assert_eq!(
            result.status,
            case["result"]["status"].as_i64().expect("status") as i32,
            "{name} status"
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result x"),
            &result.x,
            &bits_vec(&case["result"]["x"]),
        );
        assert_f64_bits_eq(
            &format!("{name} result cost"),
            result.cost,
            bits(&case["result"]["cost"]),
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result fun"),
            &result.fun,
            &bits_vec(&case["result"]["fun"]),
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result jac"),
            &result.jac,
            &bits_vec(&case["result"]["jac"]),
        );
        assert_f64_slice_bits_eq(
            &format!("{name} result grad"),
            &result.grad,
            &bits_vec(&case["result"]["grad"]),
        );
        assert_f64_bits_eq(
            &format!("{name} result optimality"),
            result.optimality,
            bits(&case["result"]["optimality"]),
        );

        checked += 1;
    }
    assert!(checked > 0, "empty trf loss fixture");
    assert_eq!(
        losses_seen,
        ["arctan", "cauchy", "huber", "soft_l1"]
            .iter()
            .map(|s| s.to_string())
            .collect::<std::collections::BTreeSet<_>>(),
        "expected every robust loss in the fixture"
    );
}
