//! Behavior of the host-LAPACK/NumPy backend's power dispatch.
//!
//! Two things are pinned here:
//!
//! 1. **Fail closed.** A configured exact backend that cannot bind the NumPy
//!    runtime it was pointed at must return a typed error. It must never answer
//!    `Ok(None)` (which would hand the solve back to the crate's own Rust
//!    `powf` and silently produce a different trajectory than the runtime the
//!    caller asked to reproduce).
//! 2. **IEEE edge behavior.** Signed zeros, infinities, and NaNs must come out
//!    of the dispatch exactly as the platform C `pow` -- and therefore NumPy's
//!    `power` ufunc -- produces them.
//!
//! The bit-for-bit comparison against a pinned x86-64 NumPy lives in the
//! fixture replay at the bottom, behind the crate's usual `SIDEREON_BITEXACT`
//! platform gate.
//!
//! Fixture provenance: `tests/fixtures/numpy_power.json` is generated by the
//! committed script
//! `crates/trust-region-least-squares/fixtures-generators/generate_numpy_power.py`.
//! Reference oracle: NumPy 2.5.0 `np.power(values, exponent)` for the vector
//! dispatch and `np.float64(base) ** exponent` for the scalar dispatch, over an
//! adversarial value set (subnormals, values straddling 1, the extremes of the
//! finite range, both signed zeros, both infinities, NaN). This payload is
//! platform- and CPU-sensitive: it must be regenerated on, and replayed on, the
//! canonical non-AVX-512 x86-64 reference host. All floating-point payloads are
//! serialized as f64 hex-bit strings and compared with `f64::to_bits`, never
//! tolerances.

use std::path::PathBuf;

use serde_json::Value;
use trust_region_least_squares::hostlapack::LapackSvd;
use trust_region_least_squares::parity::{assert_f64_slice_bits_eq, f64_from_hex};
use trust_region_least_squares::trf::ThinSvd;

#[path = "support/bitexact.rs"]
mod bitexact;

/// Adversarial bases: subnormals, the smallest normal, values straddling 1,
/// the extremes of the finite range, signed zeros, infinities, and NaN.
fn adversarial_bases() -> Vec<f64> {
    vec![
        0.0,
        -0.0,
        f64::MIN_POSITIVE * 0.5,
        f64::MIN_POSITIVE,
        1e-300,
        0.25,
        0.9999999999999999,
        1.0,
        1.0000000000000002,
        2.0,
        4.0,
        9.0,
        1.5e10,
        1e300,
        f64::MAX,
        -1.0,
        -4.0,
        f64::INFINITY,
        f64::NEG_INFINITY,
        f64::NAN,
    ]
}

/// The exponents the solver actually dispatches, plus neighbours that exercise
/// the odd-integer / non-integer branches of the C `pow` special cases.
fn adversarial_exponents() -> Vec<f64> {
    vec![-1.5, -0.5, 0.0, 0.5, 2.0, 3.0]
}

/// True when the backend's vector power takes the same scalar C `pow` path as
/// its scalar power. On an AVX-512 x86-64 host NumPy dispatches a wider SVML
/// kernel for arrays, which may differ from scalar `pow` by an ULP -- exactly
/// the divergence the crate's platform gate exists for.
fn vector_and_scalar_share_a_kernel() -> bool {
    #[cfg(target_arch = "x86_64")]
    {
        !std::is_x86_feature_detected!("avx512f")
    }
    #[cfg(not(target_arch = "x86_64"))]
    {
        true
    }
}

/// A backend bound to some library that is guaranteed to be loadable on this
/// host, so the dispatch can be exercised without a pinned NumPy install.
fn loadable_backend() -> Option<LapackSvd> {
    for candidate in [
        "/usr/lib/libSystem.B.dylib",
        "libm.so.6",
        "libc.so.6",
        "/usr/lib/libc.dylib",
        "libm.so",
        "libc.so",
    ] {
        let backend = LapackSvd::with_path(candidate);
        if backend.power_scalar(2.0, 0.5).is_ok() {
            return Some(backend);
        }
    }
    eprintln!("skipping: no loadable host library found on this platform");
    None
}

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn bits(value: &Value) -> f64 {
    f64_from_hex(value.as_str().expect("hex-bit string")).expect("valid f64 bits")
}

fn bits_vec(value: &Value) -> Vec<f64> {
    value
        .as_array()
        .expect("hex-bit array")
        .iter()
        .map(bits)
        .collect()
}

#[test]
fn unresolvable_host_runtime_fails_closed_for_vector_power() {
    let backend = LapackSvd::with_path("/nonexistent/trust-region-least-squares/libnope.so");
    let result = backend.power(&[4.0, 9.0], -0.5);
    assert!(
        result.is_err(),
        "configured host backend silently fell back: {result:?}"
    );
}

#[test]
fn unresolvable_host_runtime_fails_closed_for_scalar_power() {
    let backend = LapackSvd::with_path("/nonexistent/trust-region-least-squares/libnope.so");
    let result = backend.power_scalar(4.0, 0.5);
    assert!(
        result.is_err(),
        "configured host backend silently fell back: {result:?}"
    );
}

#[test]
fn unconfigured_host_backend_fails_closed_rather_than_declining() {
    // `power3` predates the fail-closed rule and is deliberately left alone; the
    // new hooks must not inherit its `Ok(None)` behavior. With neither an
    // explicit path nor the environment variable resolvable, both must error.
    if std::env::var_os("TRUST_REGION_LEAST_SQUARES_LAPACK_PATH").is_some()
        || std::env::var_os("TRUST_REGION_LEAST_SQUARES_NUMPY_BLAS_PATH").is_some()
    {
        eprintln!("skipping: a host LAPACK/BLAS path is configured in this environment");
        return;
    }
    let backend = LapackSvd::from_env();
    assert!(backend.power(&[4.0], -0.5).is_err());
    assert!(backend.power_scalar(4.0, 0.5).is_err());
}

#[test]
fn host_power_reproduces_the_c_pow_special_cases() {
    let Some(backend) = loadable_backend() else {
        return;
    };

    // (base, exponent, expected) drawn from the C99 `pow` special cases NumPy's
    // ufunc inherits. Compared on bits, so +0.0 and -0.0 are distinguishable.
    let cases: [(f64, f64, f64); 16] = [
        // y < 0, not an odd integer: +inf regardless of the zero's sign.
        (0.0, -0.5, f64::INFINITY),
        (-0.0, -0.5, f64::INFINITY),
        (0.0, -1.5, f64::INFINITY),
        (-0.0, -1.5, f64::INFINITY),
        // y > 0, not an odd integer: +0 regardless of the zero's sign.
        (0.0, 0.5, 0.0),
        (-0.0, 0.5, 0.0),
        // y an odd integer: the sign of the zero survives.
        (-0.0, 3.0, -0.0),
        (0.0, 3.0, 0.0),
        // x < 0 with a non-integer y is undefined -> NaN.
        (-1.0, 0.5, f64::NAN),
        (-4.0, -1.5, f64::NAN),
        // Infinities.
        (f64::INFINITY, -0.5, 0.0),
        (f64::INFINITY, 0.5, f64::INFINITY),
        (f64::NEG_INFINITY, -0.5, 0.0),
        // NaN propagation, and the two cases that override it.
        (f64::NAN, -0.5, f64::NAN),
        (f64::NAN, 0.0, 1.0),
        (1.0, f64::NAN, 1.0),
    ];

    for (base, exponent, expected) in cases {
        let scalar = backend
            .power_scalar(base, exponent)
            .expect("host scalar power")
            .expect("host scalar power result");
        assert_bits_or_nan("scalar", base, exponent, scalar, expected);

        let vector = backend
            .power(&[base], exponent)
            .expect("host vector power")
            .expect("host vector power result");
        assert_eq!(vector.len(), 1);
        assert_bits_or_nan("vector", base, exponent, vector[0], expected);
    }
}

fn assert_bits_or_nan(kind: &str, base: f64, exponent: f64, got: f64, expected: f64) {
    if expected.is_nan() {
        assert!(got.is_nan(), "{kind} pow({base:?}, {exponent:?}) = {got:?}");
    } else {
        assert_eq!(
            got.to_bits(),
            expected.to_bits(),
            "{kind} pow({base:?}, {exponent:?}) = {got:?}, expected {expected:?}"
        );
    }
}

#[test]
fn host_vector_power_matches_host_scalar_power_elementwise() {
    if !vector_and_scalar_share_a_kernel() {
        eprintln!("skipping: AVX-512 host dispatches a distinct vector kernel");
        return;
    }
    let Some(backend) = loadable_backend() else {
        return;
    };

    let bases = adversarial_bases();
    for exponent in adversarial_exponents() {
        let vector = backend
            .power(&bases, exponent)
            .expect("host vector power")
            .expect("host vector power result");
        assert_eq!(vector.len(), bases.len(), "length contract");
        for (index, &base) in bases.iter().enumerate() {
            let scalar = backend
                .power_scalar(base, exponent)
                .expect("host scalar power")
                .expect("host scalar power result");
            assert_bits_or_nan(
                &format!("index {index}"),
                base,
                exponent,
                vector[index],
                scalar,
            );
        }
    }
}

#[test]
fn host_vector_power_spans_more_than_one_simd_lane_group() {
    let Some(backend) = loadable_backend() else {
        return;
    };
    // The AVX-512 dispatch processes eight lanes at a time; a 20-element input
    // exercises two full groups plus a partial tail, and the result must be
    // exactly as long as the input.
    let bases = adversarial_bases();
    assert!(bases.len() > 16, "adversarial set must cross lane groups");
    let out = backend
        .power(&bases, -0.5)
        .expect("host vector power")
        .expect("host vector power result");
    assert_eq!(out.len(), bases.len());
}

#[test]
fn scipy_numpy_power_fixture_is_bit_exact() {
    if bitexact::skip_platform_pinned_replay() {
        return;
    }
    if std::env::var_os("TRUST_REGION_LEAST_SQUARES_LAPACK_PATH").is_none() {
        eprintln!("skipping numpy power parity: TRUST_REGION_LEAST_SQUARES_LAPACK_PATH not set");
        return;
    }
    let path = fixture_path("numpy_power.json");
    assert!(
        path.exists(),
        "missing {}; generate it in the pinned virtualenv on the canonical \
         x86-64 NumPy host with fixtures-generators/generate_numpy_power.py",
        path.display()
    );

    let raw = std::fs::read_to_string(&path).expect("read numpy power fixture");
    let doc: Value = serde_json::from_str(&raw).expect("parse numpy power fixture");
    assert_eq!(doc["schema"], "trust-region-least-squares-numpy-power-v1");
    assert_eq!(doc["numpy_version"], "2.5.0");
    // The payload is CPU- and platform-specific, like every other fixture here.
    assert_eq!(
        doc["machine"], "x86_64",
        "fixture is not from an x86-64 host"
    );

    let backend = LapackSvd::from_env();
    let mut checked = 0usize;
    for case in doc["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("name");
        let exponent = bits(&case["exponent"]);
        let values = bits_vec(&case["values"]);

        let vector = backend
            .power(&values, exponent)
            .expect("host vector power")
            .expect("host vector power result");
        assert_f64_slice_bits_eq(
            &format!("{name} np.power(values, exponent)"),
            &vector,
            &bits_vec(&case["vector_bits"]),
        );

        let scalars: Vec<f64> = values
            .iter()
            .map(|&base| {
                backend
                    .power_scalar(base, exponent)
                    .expect("host scalar power")
                    .expect("host scalar power result")
            })
            .collect();
        assert_f64_slice_bits_eq(
            &format!("{name} float(base) ** exponent"),
            &scalars,
            &bits_vec(&case["scalar_bits"]),
        );
        checked += 1;
    }
    assert!(checked > 0, "empty numpy power fixture");
}
