// Fixture provenance: `tests/fixtures/trf_loss.json` is generated by the
// committed script `crates/trust-region-least-squares/fixtures-generators/generate_trf_loss.py`.
// Reference oracle: SciPy 1.18.0 `optimize.least_squares` with TRF, dense exact
// solver, two-point Jacobian, `gtol=1e-10`, for each robust loss
// (`soft_l1`/`huber`/`cauchy`/`arctan`) across a range of `f_scale` and problem
// conditioning. Each `scale_for_robust_loss_function` application and each
// `cost_only` loss-function call along the SciPy trajectory is recorded.
// Pinned generation environment: Python 3.12.3, NumPy 2.5.0, SciPy 1.18.0,
// PyProj 3.6.1, macOS-26.5.1-arm64. All floating-point payloads are serialized as
// f64 hex-bit strings and must be compared with `f64::to_bits`, never tolerances.
//
// This suite validates the robust-loss math (rho, the trf cost `0.5*sum(rho[0])`,
// and the residual/Jacobian reweighting) bit-for-bit with no LAPACK backend. The
// end-to-end per-loss solve is validated in `hostlapack_fixtures.rs`.
use std::path::PathBuf;

use serde_json::Value;
use trust_region_least_squares::loss::{
    pairwise_sum, rho_for_loss, scale_for_robust_loss, Loss, LossFunction, Rho,
};
use trust_region_least_squares::parity::{
    assert_f64_bits_eq, assert_f64_slice_bits_eq, f64_from_hex,
};

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn bits(value: &Value) -> f64 {
    f64_from_hex(value.as_str().expect("hex-bit string")).expect("valid f64 bits")
}

fn bits_vec(value: &Value) -> Vec<f64> {
    value
        .as_array()
        .expect("hex-bit array")
        .iter()
        .map(bits)
        .collect()
}

fn loss_from_str(name: &str) -> Loss {
    match name {
        "linear" => Loss::Linear,
        "soft_l1" => Loss::SoftL1,
        "huber" => Loss::Huber,
        "cauchy" => Loss::Cauchy,
        "arctan" => Loss::Arctan,
        other => panic!("unknown loss {other}"),
    }
}

#[test]
fn scipy_robust_loss_reweighting_is_bit_exact() {
    let raw =
        std::fs::read_to_string(fixture_path("trf_loss.json")).expect("read trf loss fixture");
    let doc: Value = serde_json::from_str(&raw).expect("parse trf loss fixture");
    assert_eq!(doc["schema"], "trust-region-least-squares-trf-loss-v1");
    assert_eq!(doc["reference"]["scipy"], "1.18.0");
    assert_eq!(doc["reference"]["numpy"], "2.5.0");

    let mut losses_seen = std::collections::BTreeSet::new();
    let mut scale_checks = 0usize;
    let mut cost_only_checks = 0usize;

    for case in doc["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("case name");
        let loss = loss_from_str(case["loss"].as_str().expect("loss"));
        let f_scale = bits(&case["f_scale"]);
        let m = case["m"].as_u64().expect("m") as usize;
        losses_seen.insert(case["loss"].as_str().unwrap().to_string());
        let lf = LossFunction::new(loss, f_scale);

        for (idx, call) in case["scale_calls"]
            .as_array()
            .expect("scale calls")
            .iter()
            .enumerate()
        {
            let f_in = bits_vec(&call["f_in"]);
            let j_in = bits_vec(&call["j_in"]);
            assert_eq!(f_in.len(), m, "{name} scale {idx} f_in length");
            assert_eq!(j_in.len(), m * 3, "{name} scale {idx} j_in length");

            // Step 1: evaluate(f) must reproduce the rho SciPy handed to
            // scale_for_robust_loss_function (the f_scale-rescaled (3, m) array).
            let rho = lf.evaluate(&f_in);
            assert_f64_slice_bits_eq(
                &format!("{name} scale {idx} rho0"),
                &rho.rho0,
                &bits_vec(&call["rho0"]),
            );
            assert_f64_slice_bits_eq(
                &format!("{name} scale {idx} rho1"),
                &rho.rho1,
                &bits_vec(&call["rho1"]),
            );
            assert_f64_slice_bits_eq(
                &format!("{name} scale {idx} rho2"),
                &rho.rho2,
                &bits_vec(&call["rho2"]),
            );

            // Step 2: the trf cost 0.5 * sum(rho[0]) (NumPy pairwise sum).
            let cost = 0.5 * pairwise_sum(&rho.rho0);
            assert_f64_bits_eq(
                &format!("{name} scale {idx} cost"),
                cost,
                bits(&call["cost"]),
            );

            // Step 3: the in-place reweighting of residual and Jacobian rows.
            // Drive it from the recorded rho so this isolates the reweighting.
            let recorded_rho = Rho {
                rho0: bits_vec(&call["rho0"]),
                rho1: bits_vec(&call["rho1"]),
                rho2: bits_vec(&call["rho2"]),
            };
            let mut f_work = f_in.clone();
            let mut j_work = j_in.clone();
            scale_for_robust_loss(&mut j_work, &mut f_work, &recorded_rho, 3)
                .expect("scale_for_robust_loss");
            assert_f64_slice_bits_eq(
                &format!("{name} scale {idx} f_out"),
                &f_work,
                &bits_vec(&call["f_out"]),
            );
            assert_f64_slice_bits_eq(
                &format!("{name} scale {idx} j_out"),
                &j_work,
                &bits_vec(&call["j_out"]),
            );

            scale_checks += 1;
        }

        for (idx, call) in case["cost_only_calls"]
            .as_array()
            .expect("cost-only calls")
            .iter()
            .enumerate()
        {
            let f = bits_vec(&call["f"]);
            let cost = lf.cost_only(&f);
            assert_f64_bits_eq(
                &format!("{name} cost_only {idx}"),
                cost,
                bits(&call["cost"]),
            );
            cost_only_checks += 1;
        }
    }

    assert_eq!(
        losses_seen,
        ["arctan", "cauchy", "huber", "soft_l1"]
            .iter()
            .map(|s| s.to_string())
            .collect::<std::collections::BTreeSet<_>>(),
        "expected every robust loss in the fixture"
    );
    assert!(
        scale_checks > 0,
        "no scale_for_robust_loss applications checked"
    );
    assert!(cost_only_checks > 0, "no cost_only loss calls checked");
}

#[test]
fn huber_mask_exercises_both_branches() {
    // Directly pin the z<=1 and z>1 huber branches via rho_for_loss.
    let z = [0.25_f64, 4.0];
    let rho = rho_for_loss(Loss::Huber, &z, false);
    // z<=1: rho0=z, rho1=1, rho2=0.
    assert_f64_bits_eq("huber lo rho0", rho.rho0[0], 0.25);
    assert_f64_bits_eq("huber lo rho1", rho.rho1[0], 1.0);
    assert_f64_bits_eq("huber lo rho2", rho.rho2[0], 0.0);
    // z>1: rho0=2*sqrt(z)-1, rho1=z**-0.5, rho2=-0.5*z**-1.5.
    assert_f64_bits_eq("huber hi rho0", rho.rho0[1], 2.0 * 4.0_f64.sqrt() - 1.0);
    assert_f64_bits_eq("huber hi rho1", rho.rho1[1], 4.0_f64.powf(-0.5));
    assert_f64_bits_eq("huber hi rho2", rho.rho2[1], -0.5 * 4.0_f64.powf(-1.5));
}
