// Fixture provenance: `tests/fixtures/numdiff_2point.json` is generated by the
// committed script `crates/trust-region-least-squares/fixtures-generators/generate_numdiff.py`.
// Reference oracle: SciPy 1.11.3 `_numdiff.approx_derivative(..., method="2-point")`.
// Inputs are deterministic synthetic dense numerical problems from the generator.
// Pinned generation environment: Python 3.11.15, NumPy 1.26.0, SciPy 1.11.3,
// PyProj 3.6.1, macOS-26.5.1-arm64. All floating-point payloads are serialized as
// f64 hex-bit strings and must be compared with `f64::to_bits`, never tolerances.
use std::path::PathBuf;

use serde_json::Value;
use trust_region_least_squares::numdiff::approx_derivative_2point;
use trust_region_least_squares::parity::{
    assert_f64_bits_eq, assert_f64_slice_bits_eq, f64_from_hex,
};

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn bits(value: &Value) -> f64 {
    f64_from_hex(value.as_str().expect("hex-bit string")).expect("valid f64 bits")
}

fn bits_vec(value: &Value) -> Vec<f64> {
    value
        .as_array()
        .expect("hex-bit array")
        .iter()
        .map(bits)
        .collect()
}

fn bit_rows(value: &Value) -> Vec<Vec<f64>> {
    value
        .as_array()
        .expect("row array")
        .iter()
        .map(bits_vec)
        .collect()
}

fn model_value(case: &Value, x: &[f64]) -> Vec<f64> {
    let n = case["n"].as_u64().expect("n") as usize;
    let m = case["m"].as_u64().expect("m") as usize;
    let bias = bits_vec(&case["bias_bits"]);
    let linear = bit_rows(&case["linear_bits"]);
    let quadratic = bit_rows(&case["quadratic_bits"]);
    let cross = bit_rows(&case["cross_bits"]);

    let mut pairs = Vec::new();
    for j in 0..n {
        for k in j + 1..n {
            pairs.push((j, k));
        }
    }

    let mut out = Vec::with_capacity(m);
    for i in 0..m {
        let mut acc = bias[i];
        for (j, xj) in x.iter().copied().enumerate().take(n) {
            acc += linear[i][j] * xj;
        }
        for (j, xj) in x.iter().copied().enumerate().take(n) {
            acc += quadratic[i][j] * xj * xj;
        }
        for (p, &(j, k)) in pairs.iter().enumerate() {
            acc += cross[i][p] * (x[j] - 0.25 * x[k]) * (x[k] + 0.5);
        }
        out.push(acc);
    }
    out
}

#[test]
fn scipy_2point_numdiff_fixtures_are_bit_exact() {
    let raw =
        std::fs::read_to_string(fixture_path("numdiff_2point.json")).expect("read numdiff fixture");
    let doc: Value = serde_json::from_str(&raw).expect("parse numdiff fixture");
    assert_eq!(doc["schema"], "trust-region-least-squares-numdiff-v1");
    assert_eq!(doc["scipy_version"], "1.11.3");
    assert_eq!(doc["numpy_version"], "1.26.0");

    let mut checks = 0usize;
    for case in doc["cases"].as_array().expect("cases") {
        let id = case["id"].as_u64().expect("case id");
        let x0 = bits_vec(&case["x0_bits"]);
        let f0 = bits_vec(&case["f0_bits"]);
        let expected_f0 = model_value(case, &x0);
        assert_f64_slice_bits_eq(&format!("case {id} f0"), &expected_f0, &f0);

        let got = approx_derivative_2point(&x0, &f0, |x, out| {
            out.clear();
            out.extend(model_value(case, x));
        })
        .expect("finite difference");

        let expected_h = bits_vec(&case["h_bits"]);
        assert_f64_slice_bits_eq(&format!("case {id} h"), &got.h, &expected_h);

        let expected_one_sided: Vec<bool> = case["use_one_sided"]
            .as_array()
            .expect("use_one_sided")
            .iter()
            .map(|v| v.as_bool().expect("bool"))
            .collect();
        assert_eq!(
            got.use_one_sided, expected_one_sided,
            "case {id} use_one_sided"
        );

        let expected_points = bit_rows(&case["evaluation_points_bits"]);
        assert_eq!(
            got.evaluation_points.len(),
            expected_points.len(),
            "case {id} evaluation point count"
        );
        for (idx, expected) in expected_points.iter().enumerate() {
            assert_f64_slice_bits_eq(
                &format!("case {id} evaluation point {idx}"),
                &got.evaluation_points[idx],
                expected,
            );
        }

        let expected_jac_rows = bit_rows(&case["jacobian_bits"]);
        let expected_jac: Vec<f64> = expected_jac_rows.into_iter().flatten().collect();
        assert_f64_slice_bits_eq(&format!("case {id} jacobian"), &got.jacobian, &expected_jac);
        assert_f64_bits_eq("parser self-check", bits(&case["f0_bits"][0]), f0[0]);
        checks += 1;
    }
    assert!(checks > 0, "empty numdiff fixture");
}
