// Fixture provenance: `tests/fixtures/trf_small_dense.json` is generated by the
// committed script `crates/trust-region-least-squares/fixtures-generators/generate_trf_small_dense.py`.
// Reference oracle: SciPy 1.18.0 `optimize.least_squares` with TRF, dense exact
// solver, two-point Jacobian, linear loss, `gtol=1e-10`. Inputs are deterministic
// synthetic dense numerical problems from the generator.
// Pinned generation environment: Python 3.12.3, NumPy 2.5.0, SciPy 1.18.0,
// PyProj 3.6.1, macOS-26.5.1-arm64. All floating-point payloads are serialized as
// f64 hex-bit strings and must be compared with `f64::to_bits`, never tolerances.
use std::path::PathBuf;

use serde_json::Value;
use trust_region_least_squares::parity::{assert_f64_slice_bits_eq, f64_from_hex};
use trust_region_least_squares::trf::jacobian_2point;

#[path = "support/bitexact.rs"]
mod bitexact;

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn bits(value: &Value) -> f64 {
    f64_from_hex(value.as_str().expect("hex-bit string")).expect("valid f64 bits")
}

fn bits_vec(value: &Value) -> Vec<f64> {
    value
        .as_array()
        .expect("hex-bit array")
        .iter()
        .map(bits)
        .collect()
}

fn bits3(value: &Value) -> [f64; 3] {
    let v = bits_vec(value);
    [v[0], v[1], v[2]]
}

fn residual_values(matrix: &[f64], target: &[f64], x: &[f64]) -> Vec<f64> {
    let m = target.len();
    let mut out = Vec::with_capacity(m);
    for (i, &target_i) in target.iter().enumerate().take(m) {
        let row = i * 3;
        out.push(matrix[row] * x[0] + matrix[row + 1] * x[1] + matrix[row + 2] * x[2] - target_i);
    }
    out[0] += (0.25 * x[0]).sin() + 0.01 * x[1] * x[1];
    out[1] += (0.20 * x[1]).cos() - 0.02 * x[0] * x[2];
    out[2] += (0.15 * x[2]).sin() + 0.03 * x[0];
    out
}

#[test]
fn scipy_trf_small_dense_substrate_fixtures_are_bit_exact() {
    if bitexact::skip_platform_pinned_replay() {
        return;
    }

    let raw =
        std::fs::read_to_string(fixture_path("trf_small_dense.json")).expect("read trf fixture");
    let doc: Value = serde_json::from_str(&raw).expect("parse trf fixture");
    assert_eq!(
        doc["schema"],
        "trust-region-least-squares-trf-small-dense-v1"
    );
    assert_eq!(doc["reference"]["scipy"], "1.18.0");
    assert_eq!(doc["reference"]["numpy"], "2.5.0");

    let mut cases_checked = 0usize;
    for case in doc["cases"].as_array().expect("cases") {
        let name = case["name"].as_str().expect("case name");
        let m = case["m"].as_u64().expect("m") as usize;
        let matrix = bits_vec(&case["matrix"]);
        let target = bits_vec(&case["target"]);
        assert_eq!(matrix.len(), m * 3, "{name} matrix length");
        assert_eq!(target.len(), m, "{name} target length");

        for (idx, call) in case["fun_calls"]
            .as_array()
            .expect("fun calls")
            .iter()
            .enumerate()
        {
            let x = bits3(&call["x"]);
            let expected = bits_vec(&call["f"]);
            let actual = residual_values(&matrix, &target, &x);
            assert_f64_slice_bits_eq(&format!("{name} fun call {idx}"), &actual, &expected);
        }

        for (idx, call) in case["jac_calls"]
            .as_array()
            .expect("jac calls")
            .iter()
            .enumerate()
        {
            let x = bits3(&call["x"]);
            let f0 = bits_vec(&call["f0"]);
            let mut actual = Vec::new();
            let mut scratch = Vec::new();
            let mut fun = |x: &[f64], out: &mut Vec<f64>| {
                out.clear();
                out.extend(residual_values(&matrix, &target, x));
            };
            jacobian_2point(&mut fun, &x, &f0, &mut actual, &mut scratch)
                .expect("2-point jacobian");
            let expected = bits_vec(&call["jac"]);
            assert_f64_slice_bits_eq(&format!("{name} jac call {idx}"), &actual, &expected);
        }

        let svd_calls = case["svd_calls"].as_array().expect("svd calls");
        assert!(!svd_calls.is_empty(), "{name} expected recorded SVD calls");
        for (idx, call) in svd_calls.iter().enumerate() {
            assert_eq!(bits_vec(&call["a"]).len(), m * 3, "{name} svd {idx} a");
            assert_eq!(bits_vec(&call["u"]).len(), m * 3, "{name} svd {idx} u");
            assert_eq!(bits_vec(&call["s"]).len(), 3, "{name} svd {idx} s");
            assert_eq!(bits_vec(&call["vt"]).len(), 9, "{name} svd {idx} vt");
        }

        assert!(
            case["result"]["status"].as_i64().expect("status") >= 0,
            "{name} status"
        );

        cases_checked += 1;
    }
    assert!(cases_checked > 0, "empty trf fixture");
}
